[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_anchor_deposit = "5cSanSreu1HumAHVu5xnRcfSTytNyMcmQr83ksHMp6rf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
#wallet = "/Users/seth/.config/solana/id.json"
wallet = "~/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
